<P><FONT face="arial, helvetica, sans-serif" color=#cc3366><STRONG></STRONG></FONT>&nbsp;<FONT color=#ff0000 size=5> Welcome to : <FONT color=#330099>CRE Loaded 6.1 beta</FONT></FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#0000ff size=4>Brought to you by the CRE Loaded Project Team&nbsp;at <A href="http://www.creloaded.com/" target=_blank>creloaded.com</A>&nbsp;and the fine folks at <A href="http://www.chainreactionweb.com/" target=_blank>Chain Reaction Web</A>.</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#0000ff size=4>We have many new features this release, and some news to share.&nbsp; The Contribution List below will show a great deal of change.&nbsp; It has been updated to reflect previously unreported enhancements that took place in the 6.042 release, and the many improvements and updated contributions as well as some welcome new features.</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#0000ff size=4>First, some team news.&nbsp; Charles Williams, Jr - Project Manager for CRE Loaded 6 is leaving to pursue other opportunities.&nbsp; This release, and an upcoming upgrade to the Products Attributes system will mark his final work as Project Manager.&nbsp; We thank him for the hard work and professional programming he has brought to the project, and wish him well in his new position.</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#0000ff size=4>We welcome David M. Graham as the new Project Manager.&nbsp; Also joining us is Kerry Watson, of <A href="http://www.oscommercemanuals.com/" target=_blank>oscommercemanuals.com</A>&nbsp;.&nbsp; Kerry is our new Documentation Team Leader.&nbsp; Documentation is an important part of our project, and we are sure everyone will welcome the new users guides and technical manuals she will be producing over the next few months.</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#0000ff size=4>Thanks go to Tom O'Neill for his hard work during this transition in the final days of preparing this release.&nbsp; With team members of this caliber, CRE Loaded will certainly continue to meet ever increasing standards of excellence.&nbsp; The support of Sabrina Hogan, project manager at chainreactionweb.com and Mike Hogan, of&nbsp;Chain Reaction Web's internal Loaded 6 technical support are much appreciated.&nbsp; A special thanks to Ian Wilson's Zen Cart team, for their gracious donation of a new mySQL Backup tool.&nbsp; Those of you with large catalogs will enjoy this tool a great deal, we're sure.</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#0000ff size=4>Another new feature this release is the advent of our Google Ad Donation program.&nbsp; In the Banner Manager you will find two example banners.&nbsp; One banner each will be displayed in an infobox, and the footer 468x60 group.&nbsp; These Google Adsense banners offer an excellenet example of how to implement your own Google Adsense campaigns.&nbsp; Each is associated with the CRE Loaded Projects donation account.&nbsp;&nbsp; All you have to do to make an easy donation to the CRE Project with no out of pocket expense is leave these banners in place.&nbsp; Google will adjust the ads to fit your content.&nbsp; We would appreciate your voluntary support of this program, in support of the efforts which bring you the following features :</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#0000ff size=4></FONT>&nbsp;</P>
<P><FONT face="arial, helvetica, sans-serif" color=#cc3366><STRONG>Contributions Installed:</STRONG></FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Basic Template Structure 1.3 + Fixes</FONT>&nbsp;&nbsp;<BR></FONT><FONT face="arial, helvetica, sans-serif">Author: Brenden Vickery<BR>Modified by Paul Langford</FONT></P>
<P><FONT face=Arial><FONT color=#ff0000>Infobox Admin v1.1MS2 </FONT><FONT color=#000099><BR></FONT>Author: Paul Langford</FONT></P>
<P><FONT face=Arial><FONT color=#ff0000>Template Install &amp; Configure V1.2 <BR></FONT>Author: Paul Langford</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Credit Class/Gift Voucher/Discount Coupons 5.10b</FONT> <BR>&nbsp;Author: Ian Wilson&nbsp;<BR></FONT><FONT face="arial, helvetica, sans-serif">&nbsp;Updated for MS2 by Strider<BR>&nbsp;Additional bugfixes by Andre, Nick Stanko</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Admin With Access Levels 2.2</FONT>&nbsp;<BR>&nbsp;Author: Zaenal Muttaqin&nbsp;<BR>&nbsp;Updated for MS2 by Seth Lake</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Specials On Main Page by Default</FONT>&nbsp;<BR>&nbsp;Author: Steve Kemp</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Column Product Listing MS2</FONT>&nbsp;<BR>&nbsp;Author: David Garcia Watkins<BR>&nbsp;Updated for MS2 by Michael Sasek<BR>&nbsp;Additional Bugfixes by Souza</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Meta Tag Controller/ Generator</FONT>&nbsp;<BR>&nbsp;Author: Brenden Vickery<BR>&nbsp;Bugfixes by xxGeek</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>X-Sell MS2<BR></FONT>&nbsp;Author: Joshua Dechant</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Edit Orders 1.56 MS2<BR></FONT>&nbsp;Author: Jonathan Hilgeman</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000><FONT color=#ff0000>Category Box Enhancement 1.1</FONT><BR></FONT>&nbsp;Author:&nbsp;Nils Petersson</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Easy Populate 2.73MS2<BR></FONT>&nbsp;Author: Tim Wasson&nbsp;<BR>&nbsp;Updated for MS2 by Deborah Carney<BR>&nbsp;Bugfixes by Deborah Carney and Ian Corner<BR>&nbsp;CRE Enhancements by Tom O'Neill&nbsp;</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>OSC-Affiliate 1.09</FONT>&nbsp;<BR>&nbsp;Author: Henri Schmidhuber<BR>&nbsp;Updated to BTS v1.0 by Paul Langford</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Define Mainpage v1.2</FONT><BR>Autor: Mattice <BR>Updated for MS2 by Lee Nielsen</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><STRONG><FONT color=#ff0000>SaleMaker 2.2MS2v1.01&nbsp;<BR></FONT></STRONG>&nbsp;Author: IMarcel van Lieshout</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><STRONG><FONT color=#ff0000>MonthlySales&amp;Tax1.55</FONT><BR>&nbsp;Author: </STRONG>Fritz Clapp</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#ff0000><STRONG>Mysql Backup</STRONG></FONT></P>
<P><FONT face=Arial color=#ff0000><STRONG>&nbsp;</STRONG><FONT color=#000000><STRONG>Author: </STRONG>The Zen Cart Team</FONT></FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>WYSIWYG HTML Editor for Admin 1.7</FONT><BR>&nbsp;Author: Lee Nieslen</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>WYSIWYG HTML Editor Added to Coupons and Gift Vouchers&nbsp;<BR></FONT>&nbsp; Author: WI Benjamin</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>Dynamic Mo Pics MS2 (this contributions has been replaced) <BR></FONT>Autor: Joshua Dechant</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#ff0000>Down for Maintenance v1.1b<BR><FONT color=#000000>Author: Linda McGrath </FONT><A href="mailto:osCommerce@WebMakers.com"><FONT color=#000000>osCommerce@WebMakers.com</FONT></A><BR><FONT color=#000000>Updated by Robert Hellemans</FONT></FONT></P>
<P>
<P><FONT face="arial, helvetica, sans-serif"></FONT></P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>All-Prods-v2.4&nbsp;<BR></FONT>&nbsp;Author: v 1.0 by Mat Bennett<BR>&nbsp;Updated for Milestone MS 2.2 by Farrukh Saeed</FONT>
<P></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>UPS Choice 1.8</FONT>&nbsp;<BR>&nbsp;Author: Fritz Clapp</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>USPS Methods 2.5</FONT>&nbsp;&nbsp;<BR>&nbsp;Author: Brad Waite<BR>&nbsp;Updated for MS2 by Brad Waite/Fritz Clapp</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>FedX 1.11 MS2<BR></FONT>&nbsp;Author: Steve Fatula</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>EFSnet Payment Module<BR></FONT>&nbsp;Author: John Nelson</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>GeoTrust/SkipJack Payment Module</FONT>&nbsp;<BR>&nbsp;Author: Paul Kim</FONT></P>
<P><FONT face="arial, helvetica, sans-serif"><FONT color=#ff0000>PayBox Payment Module<BR></FONT>&nbsp;Author: Emmanuel Alliel</FONT></P>
<P><FONT face=Arial color=#ff0000>Paypal Shopping Cart IPN 2.8</FONT></P>
<P><FONT face=Arial color=#ff0000>&nbsp;<FONT color=#000000>Author : Greg Baboolal</FONT></FONT></P>
<P><FONT face=Arial>&nbsp; CRE&nbsp;Integration by David M. Graham</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#ff0000>Download_Controller v5.3 MS2.2<BR><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;Author: Linda McGrath </FONT><A href="mailto:osCOMMERCE@WebMakers.com"><FONT face="arial, helvetica, sans-serif" color=#000000>osCOMMERCE@WebMakers.com</FONT></A><BR></FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;Updated by Farrukh Saeed</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#ff0000>Attribute_Sorter_Copierv5.1<BR></FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;Author: Linda McGrath </FONT><A href="mailto:osCOMMERCE@WebMakers.com"><FONT face="arial, helvetica, sans-serif" color=#000000>osCOMMERCE@WebMakers.com</FONT></A></P>
<P><FONT face="arial, helvetica, sans-serif" color=#ff0000>osC-PrintOrder with Store Logo v1.0<BR></FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;Author: Randy Newman</FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#ff0000>News Desk 1.48.3<BR></FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;Author:Carsten aka moyashi<BR>Updates By: Wolfen aka 241</FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#ff0000>FAQ Desk 1.01<BR></FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;Author:Carsten aka moyashi</FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;</FONT></P>
<P><FONT face="arial, helvetica, sans-serif" color=#ff0000>Wish list V 2.2<BR></FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;Author:Jesse Labrocca</FONT><FONT face="arial, helvetica, sans-serif" color=#000000>&nbsp;<BR>&nbsp;Updated by Talon177</FONT></P>
<P><FONT face=Arial></FONT>&nbsp;</P>
<P><FONT face=Arial></FONT>&nbsp;</P>
